[project]
name = "macro-qgis-plugin"
version = "1.0.1"
description = "QGIS plugin for recording and playing back macros."
readme = "README.md"
license = "GPL-3.0-only"
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = ["macro-qgis-core", "qgis_plugin_tools>=1.0.0"]


[project.urls]
homepage = "https://macro-qgis-plugin.readthedocs.io"
repository = "https://github.com/Joonalai/macro-qgis-plugin"


[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.uv.build-backend]
module-name = "macro_plugin"
include = ["**/py.typed", "**/metadata.txt", "**/*.svg", "**/*.ts", "**/*.ui"]

[tool.uv.sources]
macro-qgis-core = { workspace = true }

[tool.qgis_plugin_dev_tools]
plugin_package_name = "macro_plugin"
version_number_source = "pyproject"
changelog_file_path = "../../CHANGELOG.md"
env_file_path = "../../.env"
runtime_requires = ["qgis_plugin_tools", "macro-qgis-plugin", "macro-qgis-core"]

[project.entry-points.qgis_plugin_dev_tools]
macro_plugin = "macro_plugin"
